import React from "react";
import { useState, useRef, useEffect, useCallback } from "react";

// ─── SYSTEM PROMPT ────────────────────────────────────────────────────────────
const buildSystemPrompt = (patient) => `You are HealthAI, an expert AI medical symptom assessment assistant. You are conducting a thorough, adaptive symptom interview with ${patient.name}, a ${patient.age}-year-old ${patient.sex}.

PATIENT PROFILE:
- Name: ${patient.name}
- Age: ${patient.age}
- Sex: ${patient.sex}
- Medical History: ${patient.history || "None reported"}
- Current Medications: ${patient.medications || "None reported"}
- Allergies: ${patient.allergies || "None reported"}

YOUR ROLE:
You conduct professional, empathetic symptom interviews across ALL medical domains — not limited to pain. You handle cardiology, neurology, gastroenterology, dermatology, pulmonology, psychiatry, endocrinology, infectious disease, musculoskeletal, reproductive health, and more.

INTERVIEW RULES:
1. Ask ONE focused question at a time. Never flood the patient with multiple questions.
2. Adapt your next question based on their previous answer — pursue clinically relevant threads.
3. Gather: onset/duration, location, quality/character, severity, radiation, aggravating/relieving factors, associated symptoms, timing patterns, functional impact, relevant exposures, family history if relevant.
4. After 6-10 exchanges (when you have sufficient clinical picture), say exactly: "READY_TO_GENERATE_REPORT" on its own line, then stop asking questions.
5. Be warm, professional, and reassuring. Never alarm unnecessarily.
6. If ANY emergency symptoms described (crushing chest pain with sweating/arm pain, stroke signs — FAST, severe difficulty breathing, loss of consciousness, signs of suicidal crisis), immediately respond with: "⚠️ EMERGENCY: Please call 911 or go to your nearest emergency room immediately. Do not wait." then stop.
7. Do NOT generate the report during the chat — only say READY_TO_GENERATE_REPORT when ready.`;

const REPORT_PROMPT = (patient, transcript) => `You are a clinical AI generating a comprehensive medical symptom assessment report. This is NOT a diagnosis — it is an educational health assessment to help the patient understand their symptoms and seek appropriate care.

PATIENT: ${patient.name}, ${patient.age}yo ${patient.sex}
MEDICAL HISTORY: ${patient.history || "None"}
MEDICATIONS: ${patient.medications || "None"}
ALLERGIES: ${patient.allergies || "None"}

SYMPTOM INTERVIEW TRANSCRIPT:
${transcript}

Generate a comprehensive, professional medical assessment report in the following EXACT JSON format (return ONLY valid JSON, no markdown, no extra text):

{
  "summary": "2-3 sentence clinical narrative summarizing the patient's presentation",
  "chiefComplaint": "Primary symptom in clinical language",
  "symptomProfile": [
    {"label": "Onset", "value": "..."},
    {"label": "Duration", "value": "..."},
    {"label": "Character", "value": "..."},
    {"label": "Severity", "value": ".../10"},
    {"label": "Location", "value": "..."},
    {"label": "Radiation", "value": "..."},
    {"label": "Aggravating Factors", "value": "..."},
    {"label": "Relieving Factors", "value": "..."},
    {"label": "Associated Symptoms", "value": "..."}
  ],
  "possibleConditions": [
    {
      "name": "Condition name",
      "category": "Medical specialty",
      "likelihood": 65,
      "description": "2-3 sentence explanation of this condition and why it fits the symptom profile",
      "matchingSymptoms": ["symptom1", "symptom2", "symptom3"]
    }
  ],
  "redFlags": ["red flag 1 if any", "red flag 2 if any"],
  "reassuringFactors": ["reassuring finding 1", "reassuring finding 2"],
  "triage": {
    "level": "one of: self-care | see-doctor-2-weeks | see-doctor-days | urgent-care-today | emergency-911",
    "label": "Human readable label",
    "reasoning": "2-3 sentences explaining the triage recommendation",
    "timeframe": "e.g. Within 1-2 weeks"
  },
  "recommendedNextSteps": [
    {"step": "Step title", "detail": "Detailed explanation"},
    {"step": "Step title", "detail": "Detailed explanation"},
    {"step": "Step title", "detail": "Detailed explanation"}
  ],
  "recommendedSpecialist": "Type of specialist to see",
  "testsThatMayBeOrdered": ["Test 1", "Test 2", "Test 3"],
  "selfCareAdvice": ["Advice 1", "Advice 2", "Advice 3"],
  "whenToSeekEmergencyCare": "Clear description of warning signs requiring 911/ER",
  "disclaimer": "This assessment was generated by AI and is for informational purposes only. It does not constitute medical advice, diagnosis, or treatment. Always consult a qualified healthcare provider."
}

Generate 3-5 possible conditions ordered by likelihood. Be thorough, clinically accurate, and appropriately detailed.`;

// ─── EMAIL VIA EMAILJS ────────────────────────────────────────────────────────
const sendEmail = async (patient, report, emailjsConfig) => {
  const { serviceId, templateId, publicKey } = emailjsConfig;
  if (!serviceId || !templateId || !publicKey) return false;
  try {
    const res = await fetch("https://api.emailjs.com/api/v1.0/email/send", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        service_id: serviceId,
        template_id: templateId,
        user_id: publicKey,
        template_params: {
          to_email: patient.email,
          to_name: patient.name,
          report_summary: report.summary,
          chief_complaint: report.chiefComplaint,
          triage_label: report.triage.label,
          triage_reasoning: report.triage.reasoning,
          conditions: report.possibleConditions.map(c => `${c.name} (${c.likelihood}%)`).join(", "),
          next_steps: report.recommendedNextSteps.map(s => `${s.step}: ${s.detail}`).join("\n"),
          disclaimer: report.disclaimer,
        }
      })
    });
    return res.status === 200;
  } catch { return false; }
};

// ─── COLORS / THEME ──────────────────────────────────────────────────────────
const C = {
  navy: "#04192E", blue: "#0D52D1", blue2: "#1A6BFF", teal: "#0EA5C9",
  sky: "#E8F4FF", white: "#fff", g50: "#F8FAFD", g100: "#EEF3FA",
  g200: "#D8E3F2", g400: "#8FA3BF", g600: "#4A6380",
  green: "#0FB87A", gl: "#DCFBEE", amber: "#F5A623", al: "#FEF3D6",
  red: "#E84040", rl: "#FEE2E2",
};

const triageColors = {
  "self-care": { bg: C.gl, border: "#6EE7B7", text: "#065f46", icon: "✅", label: "Self-Care" },
  "see-doctor-2-weeks": { bg: "#FEF3C7", border: "#FCD34D", text: "#92400e", icon: "📅", label: "See Doctor — Within 2 Weeks" },
  "see-doctor-days": { bg: C.al, border: "#FDBA74", text: "#9a3412", icon: "⚠️", label: "See Doctor — Within Days" },
  "urgent-care-today": { bg: "#FEE2E2", border: "#FCA5A5", text: "#7f1d1d", icon: "🚨", label: "Urgent Care — Today" },
  "emergency-911": { bg: "#7f1d1d", border: "#EF4444", text: "white", icon: "🆘", label: "EMERGENCY — Call 911" },
};

// ─── ICONS ───────────────────────────────────────────────────────────────────
const Icon = {
  ai: () => <svg width="16" height="16" viewBox="0 0 24 24" fill="white"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 14H9V8h2v8zm4 0h-2V8h2v8z" /></svg>,
  send: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="white"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z" /></svg>,
  download: () => <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7,10 12,15 17,10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
  email: () => <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>,
  check: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><polyline points="20,6 9,17 4,12"/></svg>,
  alert: () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>,
  star: () => <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>,
};

// ─── SMALL COMPONENTS ─────────────────────────────────────────────────────────
function AiAvatar() {
  return (
    <div style={{ width: 34, height: 34, borderRadius: "50%", background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, boxShadow: "0 2px 8px rgba(13,82,209,.25)" }}>
      <Icon.ai />
    </div>
  );
}

function TypingDots() {
  return (
    <div style={{ display: "flex", gap: 5, padding: "13px 16px", background: "white", borderRadius: "3px 14px 14px 14px", boxShadow: "0 1px 4px rgba(4,25,46,.08)", alignItems: "center" }}>
      {[0, 1, 2].map(i => (
        <div key={i} style={{ width: 7, height: 7, borderRadius: "50%", background: C.g200, animation: `bounce 1.2s ${i * 0.2}s infinite` }} />
      ))}
    </div>
  );
}

function Btn({ children, onClick, variant = "primary", disabled, style: extra, icon }) {
  const base = { display: "inline-flex", alignItems: "center", gap: 7, padding: "11px 22px", borderRadius: 10, fontFamily: "inherit", fontSize: 14, fontWeight: 600, cursor: disabled ? "not-allowed" : "pointer", border: "none", transition: "all .2s", opacity: disabled ? 0.6 : 1, ...extra };
  const variants = {
    primary: { background: C.blue, color: "white", boxShadow: "0 3px 12px rgba(13,82,209,.28)" },
    secondary: { background: "transparent", color: C.navy, border: `1.5px solid ${C.g200}` },
    success: { background: C.green, color: "white", boxShadow: "0 3px 12px rgba(15,184,122,.28)" },
    danger: { background: C.red, color: "white" },
    ghost: { background: C.g50, color: C.g600, border: `1.5px solid ${C.g200}` },
  };
  return <button style={{ ...base, ...variants[variant] }} onClick={onClick} disabled={disabled}>{icon}{children}</button>;
}

function Input({ label, value, onChange, type = "text", placeholder, required, options, hint }) {
  const s = { width: "100%", padding: "10px 14px", background: "white", border: `1.5px solid ${C.g200}`, borderRadius: 10, fontFamily: "inherit", fontSize: 14, color: C.navy, outline: "none", transition: "border-color .2s", boxSizing: "border-box" };
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 5 }}>
      <label style={{ fontSize: 13, fontWeight: 600, color: C.navy }}>
        {label} {required && <span style={{ color: C.red }}>*</span>}
      </label>
      {options ? (
        <select value={value} onChange={e => onChange(e.target.value)} style={{ ...s, appearance: "none" }}>
          {options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
        </select>
      ) : type === "textarea" ? (
        <textarea value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} rows={3}
          style={{ ...s, resize: "vertical", lineHeight: 1.5 }} />
      ) : (
        <input type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}
          style={s} />
      )}
      {hint && <div style={{ fontSize: 12, color: C.g400 }}>{hint}</div>}
    </div>
  );
}

// ─── REPORT PDF GENERATOR ─────────────────────────────────────────────────────
function generateReportHTML(patient, report, date) {
  const t = triageColors[report.triage.level] || triageColors["see-doctor-2-weeks"];
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<title>HealthAI Report — ${patient.name}</title>
<style>
  body{font-family:'Segoe UI',Arial,sans-serif;color:#04192E;margin:0;padding:0;background:#F8FAFD}
  .cover{background:linear-gradient(135deg,#04192E,#0A2D5A);color:white;padding:50px 48px;position:relative}
  .cover-logo{font-size:28px;font-weight:700;margin-bottom:8px}
  .cover-logo em{color:#0EA5C9;font-style:normal}
  .cover-title{font-size:36px;font-weight:300;margin:30px 0 8px;opacity:.9}
  .cover-name{font-size:22px;font-weight:600;color:#0EA5C9}
  .cover-meta{display:flex;gap:32px;margin-top:20px;opacity:.6;font-size:13px}
  .page{padding:36px 48px;max-width:820px;margin:0 auto}
  h2{font-size:20px;font-weight:700;color:#04192E;border-bottom:2px solid #EEF3FA;padding-bottom:10px;margin:32px 0 18px}
  h3{font-size:15px;font-weight:700;color:#04192E;margin:0 0 6px}
  .summary-box{background:#E8F4FF;border-left:4px solid #0D52D1;padding:18px 20px;border-radius:0 12px 12px 0;font-size:15px;line-height:1.7;color:#04192E;margin-bottom:24px}
  .triage-box{padding:20px 24px;border-radius:14px;background:${t.bg};border:2px solid ${t.border};color:${t.text};margin-bottom:28px}
  .triage-level{font-size:22px;font-weight:700;margin:6px 0 8px}
  .grid2{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:24px}
  .sym-row{display:flex;border-bottom:1px solid #EEF3FA;padding:7px 0;font-size:13px}
  .sym-label{width:180px;color:#8FA3BF;font-weight:600;flex-shrink:0}
  .sym-val{color:#04192E}
  .cond-card{background:white;border:1px solid #D8E3F2;border-radius:12px;padding:18px 20px;margin-bottom:14px}
  .cond-header{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px}
  .cond-name{font-size:15px;font-weight:700;color:#04192E}
  .cond-cat{font-size:11px;color:#8FA3BF;text-transform:uppercase;letter-spacing:.06em;margin-top:2px}
  .cond-pct{font-size:22px;font-weight:700;color:#0D52D1}
  .pct-bar{height:5px;background:#EEF3FA;border-radius:3px;overflow:hidden;margin:8px 0}
  .pct-fill{height:100%;background:linear-gradient(90deg,#0D52D1,#0EA5C9);border-radius:3px}
  .cond-desc{font-size:13px;color:#4A6380;line-height:1.6;margin-bottom:10px}
  .chip{display:inline-block;padding:3px 10px;background:#EEF3FA;border-radius:10px;font-size:11px;font-weight:500;color:#4A6380;margin:2px}
  .chip.red{background:#FEE2E2;color:#7f1d1d}
  .chip.green{background:#DCFBEE;color:#065f46}
  .step-card{display:flex;gap:14px;padding:14px 0;border-bottom:1px solid #EEF3FA}
  .step-num{width:28px;height:28px;border-radius:50%;background:#0D52D1;color:white;display:flex;align-items:center;justify-content:center;font-size:12px;font-weight:700;flex-shrink:0;margin-top:1px}
  .step-title{font-size:14px;font-weight:700;color:#04192E;margin-bottom:3px}
  .step-detail{font-size:13px;color:#4A6380;line-height:1.6}
  .tag{display:inline-block;padding:5px 12px;background:#EEF3FA;border-radius:20px;font-size:12px;color:#4A6380;margin:3px}
  .disclaimer{background:#F8FAFD;border:1px solid #D8E3F2;border-radius:10px;padding:16px 18px;font-size:12px;color:#8FA3BF;line-height:1.7;margin-top:32px}
  .emergency-box{background:#7f1d1d;color:white;padding:18px 20px;border-radius:12px;margin-bottom:20px}
  @media print{body{background:white}.page{padding:20px 28px}}
</style></head><body>
<div class="cover">
  <div class="cover-logo">Health<em>AI</em></div>
  <div style="font-size:13px;opacity:.5;margin-bottom:2px">Symptom Assessment Report</div>
  <div class="cover-title">Health Assessment</div>
  <div class="cover-name">${patient.name}</div>
  <div class="cover-meta">
    <span>Age: ${patient.age}</span><span>Sex: ${patient.sex}</span>
    <span>Date: ${date}</span><span>Report ID: HAI-${Math.random().toString(36).substr(2,8).toUpperCase()}</span>
  </div>
</div>

<div class="page">
  <h2>Clinical Summary</h2>
  <div class="summary-box">${report.summary}</div>
  <div style="margin-bottom:8px;font-size:13px;color:${C.g400}"><strong>Chief Complaint:</strong> ${report.chiefComplaint}</div>

  <h2>Triage Recommendation</h2>
  <div class="triage-box">
    <div style="font-size:13px;font-weight:600;opacity:.7">${t.icon} RECOMMENDED ACTION</div>
    <div class="triage-level">${report.triage.label}</div>
    <div style="font-size:13px;line-height:1.6">${report.triage.reasoning}</div>
    <div style="font-size:12px;font-weight:700;margin-top:10px;opacity:.8">Timeframe: ${report.triage.timeframe}</div>
  </div>

  ${report.redFlags?.length ? `
  <div class="emergency-box">
    <div style="font-weight:700;font-size:14px;margin-bottom:8px">🚨 Warning Signs — Seek Emergency Care If:</div>
    <div style="font-size:13px;line-height:1.7">${report.whenToSeekEmergencyCare}</div>
    ${report.redFlags.map(r => `<div style="margin-top:5px;font-size:12px">⚠ ${r}</div>`).join("")}
  </div>` : ""}

  <h2>Symptom Profile</h2>
  ${report.symptomProfile.map(s => `<div class="sym-row"><div class="sym-label">${s.label}</div><div class="sym-val">${s.value}</div></div>`).join("")}

  <h2>Possible Conditions</h2>
  <p style="font-size:13px;color:${C.g400};margin:-10px 0 18px">Listed by likelihood based on your symptom profile. These are possibilities, not diagnoses.</p>
  ${report.possibleConditions.map((c, i) => `
  <div class="cond-card">
    <div class="cond-header">
      <div><div class="cond-name">${i + 1}. ${c.name}</div><div class="cond-cat">${c.category}</div></div>
      <div class="cond-pct">${c.likelihood}%</div>
    </div>
    <div class="pct-bar"><div class="pct-fill" style="width:${c.likelihood}%"></div></div>
    <div class="cond-desc">${c.description}</div>
    <div>${c.matchingSymptoms.map(s => `<span class="chip">${s}</span>`).join("")}</div>
  </div>`).join("")}

  ${report.reassuringFactors?.length ? `
  <h2>Reassuring Factors</h2>
  <div>${report.reassuringFactors.map(r => `<span class="chip green">✓ ${r}</span>`).join("")}</div>` : ""}

  <h2>Recommended Next Steps</h2>
  ${report.recommendedNextSteps.map((s, i) => `
  <div class="step-card">
    <div class="step-num">${i + 1}</div>
    <div><div class="step-title">${s.step}</div><div class="step-detail">${s.detail}</div></div>
  </div>`).join("")}

  <h2>Recommended Specialist</h2>
  <div style="font-size:15px;font-weight:600;color:${C.blue};margin-bottom:18px">${report.recommendedSpecialist}</div>

  <h2>Tests That May Be Ordered</h2>
  <div>${report.testsThatMayBeOrdered.map(t => `<span class="tag">${t}</span>`).join("")}</div>

  <h2>Self-Care Advice</h2>
  <ul style="color:${C.g600};font-size:14px;line-height:1.8;padding-left:20px">
    ${report.selfCareAdvice.map(a => `<li>${a}</li>`).join("")}
  </ul>

  <div class="disclaimer">⚕️ ${report.disclaimer}</div>
</div>
</body></html>`;
}

// ─── MAIN APP ─────────────────────────────────────────────────────────────────
export default function HealthAI() {
  const [screen, setScreen] = useState("landing"); // landing | intake | chat | report
  const [patient, setPatient] = useState({ name: "", age: "", sex: "Female", email: "", history: "", medications: "", allergies: "" });
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState(null);
  const [generatingReport, setGeneratingReport] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [emailError, setEmailError] = useState("");
  const [intakeErrors, setIntakeErrors] = useState({});
  const [emailjsConfig] = useState({ serviceId: "", templateId: "", publicKey: "" }); // fill in for email
  const scrollRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages, loading, generatingReport]);

  // ── Start chat with greeting ──
  const startChat = useCallback(async () => {
    setScreen("chat");
    setLoading(true);
    try {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-20250514",
          max_tokens: 500,
          system: buildSystemPrompt(patient),
          messages: [{ role: "user", content: `Hello, I am ${patient.name}. I'd like to have my symptoms assessed.` }]
        })
      });
      const data = await res.json();
      const text = data.content?.map(b => b.type === "text" ? b.text : "").join("") || "Hello! I'm ready to help. What symptoms are you experiencing today?";
      setMessages([{ role: "ai", content: text }]);
    } catch {
      setMessages([{ role: "ai", content: `Hello ${patient.name}! I'm your HealthAI assistant. Please describe what symptoms you're experiencing and I'll guide you through a thorough assessment.` }]);
    }
    setLoading(false);
    setTimeout(() => inputRef.current?.focus(), 200);
  }, [patient]);

  // ── Generate report ──
  const generateReport = useCallback(async (msgs) => {
    setGeneratingReport(true);
    const transcript = msgs.map(m => `${m.role === "ai" ? "HealthAI" : patient.name}: ${m.content}`).join("\n\n");
    try {
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          model: "claude-sonnet-4-20250514",
          max_tokens: 4000,
          messages: [{ role: "user", content: REPORT_PROMPT(patient, transcript) }]
        })
      });
      const data = await res.json();
      let text = data.content?.map(b => b.type === "text" ? b.text : "").join("") || "";
      text = text.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      const parsed = JSON.parse(text);
      setReport(parsed);
      setScreen("report");
    } catch (e) {
      setReport({
        summary: "Your symptom assessment has been completed. Due to a processing issue, please review the conversation below and consult a healthcare provider.",
        chiefComplaint: "See conversation",
        symptomProfile: [],
        possibleConditions: [],
        triage: { level: "see-doctor-2-weeks", label: "See a Doctor", reasoning: "Based on your symptoms, we recommend consulting a healthcare provider.", timeframe: "Within 1-2 weeks" },
        recommendedNextSteps: [{ step: "Consult a physician", detail: "Please share this conversation summary with your doctor." }],
        recommendedSpecialist: "Primary Care Physician",
        testsThatMayBeOrdered: [],
        selfCareAdvice: [],
        whenToSeekEmergencyCare: "If symptoms worsen significantly, seek emergency care.",
        disclaimer: "This is an AI-generated assessment for informational purposes only.",
        redFlags: [],
        reassuringFactors: []
      });
      setScreen("report");
    }
    setGeneratingReport(false);
  }, [patient]);

  // ── Send message ──
  const sendMessage = useCallback(async (text) => {
    const trimmed = (text || input).trim();
    if (!trimmed || loading) return;
    setInput("");
    const userMsg = { role: "user", content: trimmed };
    const newMsgs = [...messages, userMsg];
    setMessages(newMsgs);
    setLoading(true);
    try {
      const apiMsgs = newMsgs.map(m => ({ role: m.role === "ai" ? "assistant" : "user", content: m.content }));
      const res = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ model: "claude-sonnet-4-20250514", max_tokens: 600, system: buildSystemPrompt(patient), messages: apiMsgs })
      });
      const data = await res.json();
      const aiText = data.content?.map(b => b.type === "text" ? b.text : "").join("") || "Could you tell me more?";
      const fullMsgs = [...newMsgs, { role: "ai", content: aiText }];
      setMessages(fullMsgs);
      if (aiText.includes("READY_TO_GENERATE_REPORT")) {
        const cleanMsgs = fullMsgs.map(m => ({ ...m, content: m.content.replace("READY_TO_GENERATE_REPORT", "").trim() })).filter(m => m.content);
        setMessages(cleanMsgs);
        setTimeout(() => generateReport(cleanMsgs), 800);
      }
    } catch {
      setMessages(prev => [...prev, { role: "ai", content: "I had a connection issue. Could you repeat that?" }]);
    }
    setLoading(false);
  }, [input, messages, loading, patient, generateReport]);

  const downloadReport = () => {
    if (!report) return;
    const html = generateReportHTML(patient, report, new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }));
    const win = window.open("", "_blank");
    win.document.write(html);
    win.document.close();
    setTimeout(() => win.print(), 500);
  };

  const handleEmailReport = async () => {
    const ok = await sendEmail(patient, report, emailjsConfig);
    if (ok) setEmailSent(true);
    else setEmailError("Email configured — see setup instructions below to enable.");
  };

  const validateIntake = () => {
    const errors = {};
    if (!patient.name.trim()) errors.name = "Name is required";
    if (!patient.age || isNaN(patient.age) || patient.age < 1 || patient.age > 120) errors.age = "Valid age required";
    if (!patient.email.trim() || !/\S+@\S+\.\S+/.test(patient.email)) errors.email = "Valid email required";
    setIntakeErrors(errors);
    return Object.keys(errors).length === 0;
  };

  // ─── SCREENS ──────────────────────────────────────────────────────────────

  // LANDING
  if (screen === "landing") return (
    <div style={{ fontFamily: "'DM Sans','Segoe UI',sans-serif", background: C.g50, minHeight: "100vh", color: C.navy }}>
      <style>{`
        @keyframes fadeUp{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
        @keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-8px)}}
        @keyframes pulse{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.5;transform:scale(1.3)}}
        @keyframes bounce{0%,60%,100%{transform:translateY(0);opacity:.5}30%{transform:translateY(-5px);opacity:1}}
        @keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}
        * { box-sizing: border-box }
      `}</style>
      {/* Nav */}
      <nav style={{ background: "rgba(255,255,255,.94)", backdropFilter: "blur(14px)", borderBottom: `1px solid ${C.g200}`, padding: "14px 5%", display: "flex", alignItems: "center", justifyContent: "space-between", position: "sticky", top: 0, zIndex: 100 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{ width: 36, height: 36, background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", borderRadius: 11, display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 3px 10px rgba(13,82,209,.3)" }}><Icon.ai /></div>
          <span style={{ fontFamily: "Georgia,serif", fontSize: 21, fontWeight: 700, color: C.navy }}>Health<em style={{ color: C.blue, fontStyle: "normal" }}>AI</em></span>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <Btn variant="secondary" onClick={() => setScreen("intake")} style={{ padding: "9px 18px", fontSize: 14 }}>Log in</Btn>
          <Btn onClick={() => setScreen("intake")} style={{ padding: "9px 18px", fontSize: 14 }}>Start Free Assessment →</Btn>
        </div>
      </nav>

      {/* Hero */}
      <div style={{ padding: "90px 5% 60px", background: `radial-gradient(ellipse 60% 50% at 70% 40%,rgba(14,165,201,.07) 0%,transparent 70%),radial-gradient(ellipse 50% 60% at 20% 70%,rgba(13,82,209,.05) 0%,transparent 60%),linear-gradient(180deg,${C.sky} 0%,${C.white} 60%)`, position: "relative" }}>
        <div style={{ maxWidth: 720, margin: "0 auto", textAlign: "center", animation: "fadeUp .6s ease forwards" }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 7, background: "rgba(13,82,209,.08)", border: "1px solid rgba(13,82,209,.15)", borderRadius: 20, padding: "5px 14px", fontSize: 12, fontWeight: 600, color: C.blue, letterSpacing: ".04em", textTransform: "uppercase", marginBottom: 24 }}>
            <div style={{ width: 6, height: 6, borderRadius: "50%", background: C.blue, animation: "pulse 2s infinite" }} />
            AI-Powered Symptom Assessment
          </div>
          <h1 style={{ fontFamily: "Georgia,serif", fontSize: "clamp(38px,6vw,64px)", fontWeight: 700, lineHeight: 1.1, letterSpacing: "-1.5px", margin: "0 0 20px" }}>
            Understand your symptoms.<br /><span style={{ color: C.blue, fontStyle: "italic", fontWeight: 400 }}>Get a real assessment.</span>
          </h1>
          <p style={{ fontSize: 18, color: C.g600, lineHeight: 1.7, maxWidth: 580, margin: "0 auto 36px", fontWeight: 300 }}>
            Describe any symptom — pain, fatigue, rashes, breathing issues, mental health, digestive problems, and more. Our AI conducts a thorough clinical interview and generates a comprehensive health report.
          </p>
          <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap", marginBottom: 48 }}>
            <Btn onClick={() => setScreen("intake")} style={{ padding: "15px 32px", fontSize: 16, borderRadius: 12 }}>
              Check my symptoms — it's free →
            </Btn>
          </div>
          <div style={{ display: "flex", gap: 28, justifyContent: "center", flexWrap: "wrap" }}>
            {["Covers all medical domains", "Comprehensive PDF report", "Results emailed to you", "HIPAA-safe · Private"].map((t, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 13, color: C.g600 }}>
                <div style={{ color: C.green }}><Icon.check /></div>{t}
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* How it works */}
      <div style={{ padding: "80px 5%", maxWidth: 1000, margin: "0 auto" }}>
        <div style={{ textAlign: "center", marginBottom: 56 }}>
          <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase", color: C.blue, marginBottom: 12 }}>How it works</div>
          <h2 style={{ fontFamily: "Georgia,serif", fontSize: "clamp(28px,4vw,42px)", fontWeight: 700, letterSpacing: "-.8px", margin: 0 }}>Four steps to clarity</h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(200px,1fr))", gap: 28 }}>
          {[
            { n: "01", title: "Enter your info", text: "Name, age, email, and brief medical history. Takes 60 seconds." },
            { n: "02", title: "Describe symptoms", text: "Tell the AI what's bothering you — in plain language. Any symptom, any body system." },
            { n: "03", title: "AI interviews you", text: "Claude asks adaptive follow-up questions until it has a complete clinical picture." },
            { n: "04", title: "Get your report", text: "Download a comprehensive PDF or have it emailed directly to you." },
          ].map((s, i) => (
            <div key={i} style={{ background: "white", border: `1px solid ${C.g200}`, borderRadius: 18, padding: 28, position: "relative", overflow: "hidden" }}>
              <div style={{ position: "absolute", top: 16, right: 16, fontFamily: "Georgia,serif", fontSize: 40, fontWeight: 700, color: C.g100, lineHeight: 1 }}>{s.n}</div>
              <div style={{ width: 44, height: 44, background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", borderRadius: 13, display: "flex", alignItems: "center", justifyContent: "center", marginBottom: 16, boxShadow: "0 4px 14px rgba(13,82,209,.25)" }}>
                <span style={{ color: "white", fontSize: 18, fontWeight: 700 }}>{i + 1}</span>
              </div>
              <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 8 }}>{s.title}</div>
              <div style={{ fontSize: 14, color: C.g600, lineHeight: 1.6 }}>{s.text}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Conditions covered */}
      <div style={{ background: C.navy, padding: "60px 5%", textAlign: "center" }}>
        <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase", color: "rgba(255,255,255,.4)", marginBottom: 12 }}>Coverage</div>
        <h2 style={{ fontFamily: "Georgia,serif", fontSize: "clamp(26px,4vw,40px)", fontWeight: 700, color: "white", marginBottom: 32, letterSpacing: "-.5px" }}>
          Every symptom, every body system
        </h2>
        <div style={{ display: "flex", flexWrap: "wrap", gap: 10, justifyContent: "center", maxWidth: 800, margin: "0 auto 36px" }}>
          {["Back & Neck Pain", "Chest Symptoms", "Headaches & Migraines", "Digestive Issues", "Skin Conditions", "Breathing Problems", "Fatigue & Sleep", "Anxiety & Depression", "Hormonal Issues", "Urinary Symptoms", "Joint & Muscle Pain", "Neurological Symptoms", "Infectious Disease", "Heart Palpitations", "Vision Changes", "Hearing Issues", "Weight Changes", "Reproductive Health"].map((c, i) => (
            <div key={i} style={{ padding: "7px 16px", background: "rgba(255,255,255,.07)", border: "1px solid rgba(255,255,255,.12)", borderRadius: 20, fontSize: 13, color: "rgba(255,255,255,.7)", fontWeight: 500 }}>{c}</div>
          ))}
        </div>
        <Btn onClick={() => setScreen("intake")} style={{ padding: "15px 32px", fontSize: 15, borderRadius: 12 }}>Start your free assessment →</Btn>
      </div>

      {/* Footer */}
      <div style={{ background: "#02101E", padding: "28px 5%", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12 }}>
        <span style={{ fontFamily: "Georgia,serif", fontSize: 16, fontWeight: 700, color: "white" }}>Health<em style={{ color: C.teal, fontStyle: "normal" }}>AI</em></span>
        <span style={{ fontSize: 12, color: "rgba(255,255,255,.25)" }}>© 2026 HealthAI · Not a substitute for professional medical advice · For informational purposes only</span>
      </div>
    </div>
  );

  // INTAKE FORM
  if (screen === "intake") return (
    <div style={{ minHeight: "100vh", background: C.g50, fontFamily: "'DM Sans','Segoe UI',sans-serif", display: "flex", flexDirection: "column" }}>
      <style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}} *{box-sizing:border-box}`}</style>
      <nav style={{ background: "white", borderBottom: `1px solid ${C.g200}`, padding: "14px 5%", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, cursor: "pointer" }} onClick={() => setScreen("landing")}>
          <div style={{ width: 32, height: 32, background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center" }}><Icon.ai /></div>
          <span style={{ fontFamily: "Georgia,serif", fontSize: 18, fontWeight: 700, color: C.navy }}>Health<em style={{ color: C.blue, fontStyle: "normal" }}>AI</em></span>
        </div>
        <div style={{ fontSize: 13, color: C.g400 }}>Step 1 of 2 — Your Information</div>
      </nav>

      <div style={{ flex: 1, display: "flex", alignItems: "flex-start", justifyContent: "center", padding: "40px 20px 60px" }}>
        <div style={{ width: "100%", maxWidth: 560, animation: "fadeUp .4s ease forwards" }}>
          <div style={{ textAlign: "center", marginBottom: 36 }}>
            <div style={{ width: 56, height: 56, background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", borderRadius: 16, display: "flex", alignItems: "center", justifyContent: "center", margin: "0 auto 16px", boxShadow: "0 6px 20px rgba(13,82,209,.25)" }}>
              <svg width="26" height="26" viewBox="0 0 24 24" fill="white"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
            </div>
            <h1 style={{ fontFamily: "Georgia,serif", fontSize: 28, fontWeight: 700, color: C.navy, margin: "0 0 8px", letterSpacing: "-.5px" }}>Tell us about yourself</h1>
            <p style={{ fontSize: 14, color: C.g600, margin: 0 }}>This information helps our AI personalize your assessment. Your report will be sent to your email.</p>
          </div>

          <div style={{ background: "white", borderRadius: 20, border: `1px solid ${C.g200}`, padding: 32, display: "flex", flexDirection: "column", gap: 20, boxShadow: "0 4px 24px rgba(4,25,46,.06)" }}>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 }}>
              <div>
                <Input label="Full Name" value={patient.name} onChange={v => setPatient(p => ({ ...p, name: v }))} placeholder="e.g. Maria Rodriguez" required />
                {intakeErrors.name && <div style={{ color: C.red, fontSize: 12, marginTop: 4 }}>{intakeErrors.name}</div>}
              </div>
              <div>
                <Input label="Age" value={patient.age} onChange={v => setPatient(p => ({ ...p, age: v }))} type="number" placeholder="e.g. 34" required />
                {intakeErrors.age && <div style={{ color: C.red, fontSize: 12, marginTop: 4 }}>{intakeErrors.age}</div>}
              </div>
            </div>
            <Input label="Biological Sex" value={patient.sex} onChange={v => setPatient(p => ({ ...p, sex: v }))} options={[{ value: "Female", label: "Female" }, { value: "Male", label: "Male" }, { value: "Non-binary / Other", label: "Non-binary / Other" }, { value: "Prefer not to say", label: "Prefer not to say" }]} required />
            <div>
              <Input label="Email Address" value={patient.email} onChange={v => setPatient(p => ({ ...p, email: v }))} type="email" placeholder="your@email.com" required hint="Your assessment report will be sent here" />
              {intakeErrors.email && <div style={{ color: C.red, fontSize: 12, marginTop: 4 }}>{intakeErrors.email}</div>}
            </div>
            <Input label="Medical History" value={patient.history} onChange={v => setPatient(p => ({ ...p, history: v }))} type="textarea" placeholder="e.g. Type 2 diabetes, hypertension, previous back surgery in 2019... (leave blank if none)" hint="Optional but helps improve accuracy" />
            <Input label="Current Medications" value={patient.medications} onChange={v => setPatient(p => ({ ...p, medications: v }))} placeholder="e.g. Metformin 500mg, Lisinopril 10mg... (or 'none')" hint="Optional" />
            <Input label="Known Allergies" value={patient.allergies} onChange={v => setPatient(p => ({ ...p, allergies: v }))} placeholder="e.g. Penicillin, NSAIDs... (or 'none')" hint="Optional" />

            <div style={{ background: C.sky, border: `1px solid ${C.g200}`, borderRadius: 10, padding: "12px 14px", fontSize: 12, color: C.g600, display: "flex", gap: 8 }}>
              <div style={{ color: C.blue, flexShrink: 0, marginTop: 1 }}><Icon.alert /></div>
              Your information is private, encrypted, and used only to generate your health assessment. We do not store or sell your data.
            </div>

            <Btn onClick={() => { if (validateIntake()) startChat(); }} style={{ width: "100%", justifyContent: "center", padding: "14px", fontSize: 15, borderRadius: 12 }}>
              Start My Assessment →
            </Btn>
          </div>
        </div>
      </div>
    </div>
  );

  // CHAT
  if (screen === "chat") return (
    <div style={{ display: "flex", flexDirection: "column", height: "100vh", fontFamily: "'DM Sans','Segoe UI',sans-serif", background: C.g50, color: C.navy }}>
      <style>{`
        @keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}
        @keyframes bounce{0%,60%,100%{transform:translateY(0);opacity:.5}30%{transform:translateY(-5px);opacity:1}}
        @keyframes blink{0%,100%{opacity:1}50%{opacity:.3}}
        @keyframes spin{to{transform:rotate(360deg)}}
        *{box-sizing:border-box}
      `}</style>
      {/* Topbar */}
      <div style={{ background: "white", borderBottom: `1px solid ${C.g200}`, padding: "12px 22px", display: "flex", alignItems: "center", justifyContent: "space-between", flexShrink: 0 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <div style={{ width: 32, height: 32, background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center" }}><Icon.ai /></div>
          <div>
            <div style={{ fontFamily: "Georgia,serif", fontSize: 16, fontWeight: 700 }}>HealthAI Assessment</div>
            <div style={{ fontSize: 11, color: C.g400 }}>Speaking with {patient.name} · AI-powered · Clinically informed</div>
          </div>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 5, padding: "4px 10px", borderRadius: 10, background: C.gl, fontSize: 12, fontWeight: 600, color: "#065f46" }}>
            <div style={{ width: 5, height: 5, borderRadius: "50%", background: C.green, animation: "blink 1.5s infinite" }} />
            AI Connected
          </div>
          <div style={{ fontSize: 12, color: C.g400 }}>{messages.length} exchanges</div>
        </div>
      </div>

      {/* Generating overlay */}
      {generatingReport && (
        <div style={{ position: "absolute", inset: 0, background: "rgba(4,25,46,.7)", backdropFilter: "blur(8px)", zIndex: 50, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 20 }}>
          <div style={{ width: 64, height: 64, border: "4px solid rgba(255,255,255,.2)", borderTop: "4px solid white", borderRadius: "50%", animation: "spin 1s linear infinite" }} />
          <div style={{ textAlign: "center", color: "white" }}>
            <div style={{ fontFamily: "Georgia,serif", fontSize: 22, fontWeight: 700, marginBottom: 8 }}>Generating Your Report</div>
            <div style={{ fontSize: 14, opacity: .7 }}>Analyzing your symptoms and preparing a comprehensive assessment…</div>
          </div>
        </div>
      )}

      {/* Chat */}
      <div ref={scrollRef} style={{ flex: 1, overflowY: "auto", padding: "22px 0" }}>
        <div style={{ maxWidth: 660, margin: "0 auto", padding: "0 20px", display: "flex", flexDirection: "column", gap: 16 }}>
          {messages.map((msg, i) => {
            const isAI = msg.role === "ai";
            return (
              <div key={i} style={{ display: "flex", flexDirection: "column", gap: 5, animation: "fadeUp .3s ease forwards", opacity: 0, animationDelay: `${Math.min(i * 0.05, 0.3)}s` }}>
                <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: ".04em", textTransform: "uppercase", color: C.g400, paddingLeft: isAI ? 44 : 0, textAlign: isAI ? "left" : "right" }}>
                  {isAI ? "HealthAI" : patient.name}
                </div>
                <div style={{ display: "flex", gap: 10, flexDirection: isAI ? "row" : "row-reverse" }}>
                  {isAI && <AiAvatar />}
                  <div style={{ maxWidth: "84%", padding: "12px 16px", borderRadius: isAI ? "3px 14px 14px 14px" : "14px 3px 14px 14px", fontSize: 14.5, lineHeight: 1.65, background: isAI ? "white" : "linear-gradient(135deg,#0D52D1,#1A6BFF)", color: isAI ? C.navy : "white", boxShadow: isAI ? "0 1px 4px rgba(4,25,46,.08)" : "0 2px 10px rgba(13,82,209,.2)" }}>
                    {msg.content.split("\n").map((line, li) => <div key={li}>{line || <br />}</div>)}
                  </div>
                </div>
              </div>
            );
          })}
          {loading && (
            <div style={{ display: "flex", gap: 10, animation: "fadeUp .25s ease forwards" }}>
              <AiAvatar />
              <TypingDots />
            </div>
          )}
        </div>
      </div>

      {/* Input */}
      <div style={{ background: "white", borderTop: `1px solid ${C.g200}`, padding: "13px 22px 18px", flexShrink: 0 }}>
        <div style={{ maxWidth: 660, margin: "0 auto", display: "flex", gap: 8, alignItems: "flex-end", background: C.g100, border: `1.5px solid ${C.g200}`, borderRadius: 14, padding: "9px 9px 9px 14px" }}>
          <textarea
            ref={inputRef}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); } }}
            placeholder="Type your answer here… (press Enter to send)"
            rows={1}
            style={{ flex: 1, background: "transparent", border: "none", outline: "none", fontFamily: "inherit", fontSize: 14, color: C.navy, resize: "none", maxHeight: 120, minHeight: 22, lineHeight: 1.5 }}
          />
          <button onClick={() => sendMessage()} disabled={loading || !input.trim()} style={{ width: 36, height: 36, background: loading || !input.trim() ? C.g200 : C.blue, border: "none", borderRadius: 9, cursor: loading || !input.trim() ? "not-allowed" : "pointer", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0, transition: "background .2s" }}>
            <Icon.send />
          </button>
        </div>
        <div style={{ maxWidth: 660, margin: "7px auto 0", fontSize: 11, color: C.g400, textAlign: "center" }}>
          🔒 Private · Encrypted · Not a medical diagnosis · The AI will generate your report when it has enough information
        </div>
      </div>
    </div>
  );

  // REPORT
  if (screen === "report" && report) {
    const t = triageColors[report.triage?.level] || triageColors["see-doctor-2-weeks"];
    const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
    return (
      <div style={{ fontFamily: "'DM Sans','Segoe UI',sans-serif", background: C.g50, minHeight: "100vh", color: C.navy }}>
        <style>{`@keyframes fadeUp{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}} *{box-sizing:border-box}`}</style>
        {/* Nav */}
        <nav style={{ background: "white", borderBottom: `1px solid ${C.g200}`, padding: "14px 5%", display: "flex", alignItems: "center", justifyContent: "space-between", position: "sticky", top: 0, zIndex: 50 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ width: 32, height: 32, background: "linear-gradient(135deg,#0D52D1,#0EA5C9)", borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center" }}><Icon.ai /></div>
            <span style={{ fontFamily: "Georgia,serif", fontSize: 18, fontWeight: 700, color: C.navy }}>Health<em style={{ color: C.blue, fontStyle: "normal" }}>AI</em> — Your Report</span>
          </div>
          <div style={{ display: "flex", gap: 10 }}>
            <Btn variant="ghost" onClick={downloadReport} icon={<Icon.download />} style={{ fontSize: 13, padding: "9px 16px" }}>Download / Print PDF</Btn>
            <Btn variant="success" onClick={handleEmailReport} icon={<Icon.email />} style={{ fontSize: 13, padding: "9px 16px" }}>
              {emailSent ? "✓ Sent!" : `Email to ${patient.email}`}
            </Btn>
          </div>
        </nav>

        {emailError && (
          <div style={{ background: C.al, border: `1px solid ${C.amber}`, padding: "10px 5%", fontSize: 13, color: "#92400e", display: "flex", gap: 8 }}>
            <Icon.alert /> {emailError} — To enable email: set up EmailJS and add your serviceId/templateId/publicKey in the code.
          </div>
        )}
        {emailSent && (
          <div style={{ background: C.gl, border: `1px solid #6EE7B7`, padding: "10px 5%", fontSize: 13, color: "#065f46" }}>
            ✅ Report successfully sent to {patient.email}
          </div>
        )}

        <div style={{ maxWidth: 1020, margin: "0 auto", padding: "36px 22px 80px" }}>
          {/* Header card */}
          <div style={{ background: "linear-gradient(135deg,#04192E,#0A2D5A)", borderRadius: 20, padding: "34px 38px", marginBottom: 26, position: "relative", overflow: "hidden", animation: "fadeUp .4s ease forwards" }}>
            <div style={{ position: "absolute", right: -40, top: -40, width: 200, height: 200, background: "radial-gradient(circle,rgba(14,165,201,.15) 0%,transparent 70%)" }} />
            <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: ".08em", textTransform: "uppercase", color: "rgba(255,255,255,.4)", marginBottom: 8 }}>Health Assessment Report · {date}</div>
            <div style={{ fontFamily: "Georgia,serif", fontSize: 28, fontWeight: 700, color: "white", marginBottom: 10, lineHeight: 1.2 }}>
              {patient.name}'s Symptom Assessment
            </div>
            <div style={{ fontSize: 14, color: "rgba(255,255,255,.55)", marginBottom: 20, lineHeight: 1.7, maxWidth: 600 }}>{report.summary}</div>
            <div style={{ display: "flex", gap: 20, flexWrap: "wrap" }}>
              {[["Chief Complaint", report.chiefComplaint], ["Age", `${patient.age}yo ${patient.sex}`], ["Specialist Recommended", report.recommendedSpecialist]].map(([k, v]) => (
                <div key={k}>
                  <div style={{ fontSize: 10, fontWeight: 600, textTransform: "uppercase", letterSpacing: ".06em", color: "rgba(255,255,255,.35)", marginBottom: 2 }}>{k}</div>
                  <div style={{ fontSize: 13, fontWeight: 600, color: "rgba(255,255,255,.85)" }}>{v}</div>
                </div>
              ))}
            </div>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 320px", gap: 22, alignItems: "start" }}>
            {/* Main col */}
            <div>
              {/* Triage */}
              <Section title="Triage Recommendation" icon="⚖️">
                <div style={{ padding: "18px 20px", borderRadius: 14, background: t.bg, border: `2px solid ${t.border}`, color: t.text }}>
                  <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".06em", textTransform: "uppercase", opacity: .7, marginBottom: 6 }}>{t.icon} Recommended Action</div>
                  <div style={{ fontFamily: "Georgia,serif", fontSize: 22, fontWeight: 700, marginBottom: 10 }}>{report.triage.label}</div>
                  <div style={{ fontSize: 14, lineHeight: 1.6, marginBottom: 8 }}>{report.triage.reasoning}</div>
                  <div style={{ fontSize: 13, fontWeight: 700, opacity: .7 }}>Timeframe: {report.triage.timeframe}</div>
                </div>
              </Section>

              {/* Conditions */}
              <Section title="Possible Conditions" icon="🔬" subtitle="Listed by likelihood · Not a diagnosis">
                {report.possibleConditions?.map((c, i) => (
                  <div key={i} style={{ background: "white", border: `1px solid ${C.g200}`, borderRadius: 14, padding: "18px 20px", marginBottom: 14 }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 8 }}>
                      <div>
                        <div style={{ fontSize: 16, fontWeight: 700, color: C.navy, marginBottom: 3 }}>{i + 1}. {c.name}</div>
                        <div style={{ fontSize: 11, fontWeight: 600, textTransform: "uppercase", letterSpacing: ".05em", color: C.g400 }}>{c.category}</div>
                      </div>
                      <div style={{ fontFamily: "Georgia,serif", fontSize: 26, fontWeight: 700, color: i === 0 ? C.blue : C.g400 }}>{c.likelihood}%</div>
                    </div>
                    <div style={{ height: 5, background: C.g100, borderRadius: 3, overflow: "hidden", marginBottom: 12 }}>
                      <div style={{ width: `${c.likelihood}%`, height: "100%", background: i === 0 ? "linear-gradient(90deg,#0D52D1,#0EA5C9)" : C.g200, borderRadius: 3, transition: "width 1s ease" }} />
                    </div>
                    <div style={{ fontSize: 14, color: C.g600, lineHeight: 1.65, marginBottom: 12 }}>{c.description}</div>
                    <div style={{ display: "flex", flexWrap: "wrap", gap: 5 }}>
                      {c.matchingSymptoms?.map((s, si) => (
                        <span key={si} style={{ padding: "3px 10px", background: C.g100, borderRadius: 10, fontSize: 12, color: C.g600, fontWeight: 500 }}>{s}</span>
                      ))}
                    </div>
                  </div>
                ))}
              </Section>

              {/* Next Steps */}
              <Section title="Recommended Next Steps" icon="📋">
                {report.recommendedNextSteps?.map((s, i) => (
                  <div key={i} style={{ display: "flex", gap: 14, padding: "14px 0", borderBottom: `1px solid ${C.g100}` }}>
                    <div style={{ width: 28, height: 28, borderRadius: "50%", background: C.blue, color: "white", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 12, fontWeight: 700, flexShrink: 0, marginTop: 1 }}>{i + 1}</div>
                    <div>
                      <div style={{ fontSize: 14, fontWeight: 700, color: C.navy, marginBottom: 4 }}>{s.step}</div>
                      <div style={{ fontSize: 13, color: C.g600, lineHeight: 1.65 }}>{s.detail}</div>
                    </div>
                  </div>
                ))}
              </Section>

              {/* Symptom Profile */}
              <Section title="Symptom Profile" icon="📊">
                {report.symptomProfile?.map((s, i) => (
                  <div key={i} style={{ display: "flex", padding: "9px 0", borderBottom: `1px solid ${C.g100}`, fontSize: 14 }}>
                    <div style={{ width: 180, color: C.g400, fontWeight: 600, flexShrink: 0 }}>{s.label}</div>
                    <div style={{ color: C.navy }}>{s.value}</div>
                  </div>
                ))}
              </Section>

              {/* Tests */}
              {report.testsThatMayBeOrdered?.length > 0 && (
                <Section title="Tests That May Be Ordered" icon="🧪">
                  <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                    {report.testsThatMayBeOrdered.map((t, i) => (
                      <span key={i} style={{ padding: "6px 14px", background: C.sky, border: `1px solid ${C.g200}`, borderRadius: 20, fontSize: 13, color: C.blue, fontWeight: 500 }}>{t}</span>
                    ))}
                  </div>
                </Section>
              )}

              {/* Self-care */}
              {report.selfCareAdvice?.length > 0 && (
                <Section title="Self-Care Advice" icon="💊">
                  <ul style={{ margin: 0, padding: "0 0 0 20px", color: C.g600, fontSize: 14, lineHeight: 1.8 }}>
                    {report.selfCareAdvice.map((a, i) => <li key={i}>{a}</li>)}
                  </ul>
                </Section>
              )}
            </div>

            {/* Sidebar */}
            <div style={{ position: "sticky", top: 80 }}>
              {/* Emergency */}
              <div style={{ background: C.rl, border: `1.5px solid #FCA5A5`, borderRadius: 16, padding: 20, marginBottom: 18 }}>
                <div style={{ fontSize: 13, fontWeight: 700, color: "#7f1d1d", marginBottom: 8 }}>🚨 Seek Emergency Care If:</div>
                <div style={{ fontSize: 13, color: "#7f1d1d", lineHeight: 1.6 }}>{report.whenToSeekEmergencyCare}</div>
              </div>

              {/* Red flags */}
              {report.redFlags?.length > 0 && (
                <SideCard title="⚠️ Red Flags Noted">
                  {report.redFlags.map((r, i) => (
                    <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 7, padding: "6px 0", borderBottom: `1px solid ${C.g100}`, fontSize: 13, color: "#92400e" }}>
                      <div style={{ flexShrink: 0, marginTop: 2 }}>⚠</div>{r}
                    </div>
                  ))}
                </SideCard>
              )}

              {/* Reassuring */}
              {report.reassuringFactors?.length > 0 && (
                <SideCard title="✅ Reassuring Factors">
                  {report.reassuringFactors.map((r, i) => (
                    <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 7, padding: "6px 0", borderBottom: `1px solid ${C.g100}`, fontSize: 13, color: "#065f46" }}>
                      <div style={{ flexShrink: 0, marginTop: 2 }}>✓</div>{r}
                    </div>
                  ))}
                </SideCard>
              )}

              {/* Profile */}
              <SideCard title="👤 Patient Profile">
                {[["Name", patient.name], ["Age", patient.age], ["Sex", patient.sex], ["Email", patient.email], ["History", patient.history || "None"], ["Medications", patient.medications || "None"], ["Allergies", patient.allergies || "None"]].map(([k, v]) => (
                  <div key={k} style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: `1px solid ${C.g100}`, fontSize: 13 }}>
                    <span style={{ color: C.g400, fontWeight: 600 }}>{k}</span>
                    <span style={{ color: C.navy, fontWeight: 500, textAlign: "right", maxWidth: "60%" }}>{v}</span>
                  </div>
                ))}
              </SideCard>

              {/* Actions */}
              <SideCard title="📤 Share This Report">
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  <Btn onClick={downloadReport} variant="ghost" icon={<Icon.download />} style={{ width: "100%", justifyContent: "center", fontSize: 13, padding: "10px" }}>Download / Print PDF</Btn>
                  <Btn onClick={handleEmailReport} variant="success" icon={<Icon.email />} style={{ width: "100%", justifyContent: "center", fontSize: 13, padding: "10px" }}>
                    {emailSent ? "✓ Sent!" : "Email Report"}
                  </Btn>
                  <Btn onClick={() => { setScreen("chat"); setMessages([]); setReport(null); startChat(); }} variant="secondary" style={{ width: "100%", justifyContent: "center", fontSize: 13, padding: "10px" }}>Start New Assessment</Btn>
                </div>
              </SideCard>

              <div style={{ background: C.g50, border: `1px solid ${C.g200}`, borderRadius: 12, padding: "13px 15px", fontSize: 12, color: C.g400, lineHeight: 1.7 }}>
                ⚕️ {report.disclaimer}
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return <div style={{ padding: 40, textAlign: "center" }}>Loading…</div>;
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function Section({ title, icon, subtitle, children }) {
  return (
    <div style={{ background: "white", border: `1px solid ${C.g200}`, borderRadius: 16, overflow: "hidden", marginBottom: 20 }}>
      <div style={{ padding: "18px 22px", borderBottom: `1px solid ${C.g200}`, display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <div style={{ fontSize: 15, fontWeight: 700, color: C.navy, display: "flex", alignItems: "center", gap: 8 }}>
          <span>{icon}</span>{title}
        </div>
        {subtitle && <span style={{ fontSize: 12, color: C.g400 }}>{subtitle}</span>}
      </div>
      <div style={{ padding: "20px 22px" }}>{children}</div>
    </div>
  );
}

function SideCard({ title, children }) {
  return (
    <div style={{ background: "white", border: `1px solid ${C.g200}`, borderRadius: 14, overflow: "hidden", marginBottom: 16 }}>
      <div style={{ padding: "13px 18px", borderBottom: `1px solid ${C.g100}`, fontSize: 13, fontWeight: 700, color: C.navy }}>{title}</div>
      <div style={{ padding: "12px 18px" }}>{children}</div>
    </div>
  );
}
